[versions]
agp = "9.2.1"
kotlin = "2.2.10"
ksp = "2.3.2"

[libraries]
# dependencies declared directly as strings in app/build.gradle.kts

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
